sudo: required

notifications:
    email:
        recipients:
            - munaro.michael@gmail.com
        on_success:
                never
        on_failure:
                change

branches:
    only:
        - master

services:
    - docker

before_install:
    - docker pull scalatekids/scalatekids-latex

script:
    - docker run --rm -i --net=none -v `pwd`:/root/actorbase scalatekids/scalatekids-latex:latest verify
    - docker run --rm -i --net=none -v `pwd`:/root/actorbase scalatekids/scalatekids-latex:latest verifygloss
    - echo "y" | docker run --rm -i --net=none -v `pwd`:/root/actorbase scalatekids/scalatekids-latex:latest build
    - docker run --rm -i --net=none -v `pwd`:/root/actorbase scalatekids/scalatekids-latex:latest readability
