sudo: required

branches:
    only:
        - dev

services:
    - docker

before_install:
    - docker pull codep/scalatekids-env

script:
    - echo "y" | docker run --rm -i --net=none -v `pwd`:/latex -v `pwd`/img/:/latex/img codep/scalatekids-env:latest build

after_success:
    - git config --global user.email ${GIT_EMAIL}
    - git config --global user.name ${GIT_NAME}
    - git clone --branch=