sudo: required

branches:
    only:
        - dev

services:
    - docker

before_install:
    - docker pull codep/scalatekids-env

script:
    - echo "y" | docker run --rm -i --net=none -v `pwd`:/latex -v `pwd`/img/:/latex/img codep/scalatekids-env:latest build

after_success:
    - git config --global user.email ${GIT_EMAIL}
    - git config --global user.name ${GIT_NAME}
    - git clone --branch=production https://github.com/Scalatekids/Actorbase-Documents travis-build
    - mkdir -p travis-build/RR/Interni && cp -p $(find . -name 'Norme*pdf') travis-build/RR/Interni
    - cp -p $(find . -name 'Studio*pdf') travis-build/RR/Interni
    - mkdir -p travis-build/RR/Esterni && cp -p $(find . -name 'PianiDiProgetto*pdf') travis-build/RR/Esterni
    - cp -p $(find . -name 'PianoDiQualifica*pdf') travis-build/RR/Esterni
    - cp -p $(find . -name 'Analisi*pdf') travis-build/RR/Esterni
    - cp -p $(find . -name 'Glossario*pdf') travis-build/RR/Esterni
    - cd travis-build && git add .
    - git commit -m "Travis CI autocommit, build ${TRAVIS_BUILD_NUMBER}"
    - git push -f origin production